app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, session, send_file, jsonify, make_response, abort
from sqlalchemy import func
from flask_login import login_user, logout_user, current_user, login_required
from .models import db, Users, Products, Members, Sale, saleDetails
from .roleRequired import role_required
from .forms import LoginForm
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
import os
from datetime import datetime, date
import uuid
import io
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from io import BytesIO


ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

app = Blueprint('main', __name__)

@app.route('/', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            session['user_id'] = user.id
            session['user_name'] = user.username
            session['role'] = user.role
            flash(f"Selamat datang, {user.username}!", "success")
            return redirect(url_for('main.dashboard'))
        else:
            flash('Username atau password salah', 'danger')
    return render_template('login.html', form=form)

# >>>>>>>>>>>>>>>>>>>>>>>>>> DASHBOARD API <<<<<<<<<<<<<<<<<<<<<<<<<< #

def hitung_total_penjualan_hari_ini():
    today = date.today()

    total = (
        Sale.query
        .filter(Sale.created_at == today)
        .count()
    )

    total_member = (
        Sale.query
        .filter(Sale.created_at == today, Sale.member_id.isnot(None))
        .count()
    )

    total_non_member = (
        Sale.query
        .filter(Sale.created_at == today, Sale.member_id.is_(None))
        .count()
    )

    return total, total_member, total_non_member


def get_data_dashboard_admin():
    today = date.today()
    start_date = today.replace(day=1)

    results = (
        db.session.query(Sale.created_at, func.count(Sale.id))
        .filter(Sale.created_at >= start_date)
        .group_by(Sale.created_at)
        .order_by(Sale.created_at)
        .all()
    )

    penjualan_harian = [(tgl.strftime('%d %b'), jumlah) for tgl, jumlah in results]
    penjualan_harian = penjualan_harian or []

    member_count = Sale.query.filter(Sale.member_id.isnot(None)).count() or 0
    non_member_count = Sale.query.filter(Sale.member_id.is_(None)).count() or 0

    product_query = (
        db.session.query(saleDetails.product_name, func.count(saleDetails.id))
        .group_by(saleDetails.product_name)
        .order_by(func.count(saleDetails.id).desc())
        .all()
    )

    product_labels = [p[0] for p in product_query]
    product_values = [p[1] for p in product_query]

    return penjualan_harian, member_count, non_member_count, start_date, today, product_labels, product_values


@app.route('/dashboard')
@login_required
def dashboard():
    if current_user.role == 'admin':
        penjualan_harian, member_count, non_member_count, start_date, today, product_labels, product_values = get_data_dashboard_admin()

        return render_template(
            'dashboard/dashboard_admin.html',
            penjualan_harian=penjualan_harian,
            member_count=member_count,
            non_member_count=non_member_count,
            start_date=start_date,
            today=today,
            product_labels=product_labels,
            product_values=product_values
        )
    
    elif current_user.role == 'petugas':
        total_penjualan, member_count, non_member_count = hitung_total_penjualan_hari_ini()
        today = date.today()
        return render_template(
            'dashboard/dashboard_petugas.html',
            total_penjualan=total_penjualan,
            today=today,
            non_member_count=non_member_count,
            member_count=member_count,
        )
    
    else:
        flash("Role tidak dikenal", "danger")
        return redirect(url_for('login.html'))





@app.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    flash("Berhasil logout", "info")
    return redirect(url_for('main.login'))


# >>>>>>>>>>>>>>>>>>>>>>>>>>     PRODUK API     <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< #
@app.route('/products', methods=['GET'])
@login_required
def read_all_produk():
    all_products = Products.query.all()
    return render_template('product/product.html', products=all_products)

@app.route('/sales/<int:sale_id>/detail', methods=['GET'])
@login_required
def sale_detail(sale_id):
    sale_detail_items = saleDetails.query.filter_by(sale_id=sale_id).all()

    if not sale_detail_items:
        abort(404, description="Detail penjualan tidak ditemukan")

    sale = Sale.query.get_or_404(sale_id)

    return render_template('sale/sale_detail_modal.html', sale=sale, sale_detail_items=sale_detail_items)



@app.route('/products/tambah', methods=['GET', 'POST'])
@login_required
@role_required('admin')
def tambah_produk():
    if request.method == 'POST':
        name = request.form['name']
        price =  request.form['price']
        stock = request.form['stock']
        image_file = request.files.get('image')

        if not name or not price or not stock:
            flash("Semua field wajib diisi")
            return redirect(url_for('tambah_produk'))
        
        
        try:
            price =  float(price.replace('.', '').replace(',', ''))
            stock = int(stock)
        except ValueError:
            flash("Format price atau stock tidak sesuai dengan yang diharapkan")
            return redirect(url_for('tambah_produk'))
        
        if image_file and image_file.filename != '':
            if '.' in image_file.filename and image_file.filename.rsplit('.', 1)[1].lower() in ['jpg', 'jpeg', 'png', 'gif']:
                filename = secure_filename(image_file.filename)
                image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                image_file.save(image_path)
            else:
                flash("Ekstensi file tidak didukung", "danger")
                return redirect(url_for('produk.tambah_produk'))
        else:
            filename = None

        
        new_produk = Products(name=name, price=price, stock=stock, image=filename)
        db.session.add(new_produk)
        db.session.commit()
        flash("Products berhasil ditambahkan")
        return redirect(url_for('main.read_all_produk'))

    return render_template('product/tambah_produk.html')


@app.route('/product/delete/<int:product_id>', methods=['GET', 'POST'])
@login_required
@role_required('admin')
def delete_product(product_id):
    product = Products.query.get_or_404(product_id)
    db.session.delete(product)
    db.session.commit()
    flash("Berhasil menghapus product")
    return redirect(url_for('main.read_all_produk'))

@app.route('/product/edit/<int:product_id>', methods=['GET', 'POST'])
@login_required
@role_required('admin')
def edit_product(product_id):
    product = Products.query.get_or_404(product_id)

    if request.method == 'POST':
        product.name = request.form['name']
        product.price = request.form['price']
        product.stock = request.form['stock']
        image = request.files.get('image_file')

        if image and image.filename != '':
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            product.image = filename

        db.session.commit()
        flash('Produk berhasil diperbarui!', 'success')
        return redirect(url_for('main.read_all_produk'))

    return render_template('product/edit_product.html', product=product)


# >>>>>>>>>>>>>>>>>>>>>>> PENJUALAN API <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< #

@app.route('/sale', methods=['GET'])
@login_required
def get_all_sale():
    all_sale = Sale.query.all()
    print(all_sale)
    return render_template('sale/sale.html', sales=all_sale)


@app.route('/sale/create', methods=['GET', 'POST'])
@login_required
def create_sale():
    products = Products.query.all()
    if request.method == 'POST':
        items = []
        total_price = 0

        for product in products:
            qty = int(request.form.get(f'quantities[{product.id}]', 0))
            if qty > 0:
                if qty > product.stock:
                    flash(f"Stok produk {product.name} tidak mencukupi", "danger")
                    return redirect(url_for('main.create_sale'))

                subtotal = qty * product.price
                items.append({
                    'product_id': product.id,
                    'product_name': product.name,
                    'quantity': qty,
                    'price': product.price,
                    'subtotal': subtotal,
                    'image': product.image
                })
                total_price += subtotal

        if not items:
            flash("Pilih setidaknya satu produk.", "warning")
            return redirect(url_for('main.create_sale'))

        session['pending_sale'] = {
            'items': items,
            'total_price': total_price
        }
        return redirect(url_for('main.payment_step1'))

    return render_template('sale/create_sale.html', products=products)

@app.route('/sale/payment/step1', methods=['GET', 'POST'])
@login_required
def payment_step1():
    if 'pending_sale' not in session:
        return redirect(url_for('main.create_sale'))

    if request.method == 'POST':
        status = request.form['is_member']
        phone = request.form.get('phone_number')

app/templates/product/edit_product.html
{% extends "layout.html" %}
{% block title %}Edit Product{% endblock %}

{% block content %}
<h2 class="mb-4">Edit Produk</h2>

<form method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="name" class="form-label">Nama Produk</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ product.name }}" required>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Harga</label>
        <input type="number" class="form-control" id="price" name="price" value="{{ product.price }}" required>
    </div>
    <div class="mb-3">
        <label for="stock" class="form-label">Stok</label>
        <input type="number" class="form-control" id="stock" name="stock" value="{{ product.stock }}" required>
    </div>
    <div class="mb-3">
        <label for="image_file" class="form-label">Image</label>
        <input type="file" class="form-control" id="image_file" name="image_file">
        {% if product.image %}
        <div class="mt-2">
            <img src="{{ url_for('static', filename='product/' ~ product.image) }}" width="120">
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
    <a href="{{ url_for('main.read_all_produk') }}" class="btn btn-secondary">Batal</a>
</form>
{% endblock %}

app/templates/product/product.html
{% extends "layout.html" %}
{% block title %}Products{% endblock %}

{% block content %}
<h2 class="mb-4">Daftar Products</h2>

<table class="table table-bordered table-hover">
    <thead class="table-primary">
        <tr>
            <th>No</th>
            <th>Nama Products</th>
            <th>Harga</th>
            <th>Stok</th>
            <th>Image</th>
            {% if current_user.role == 'admin'  %}
            <th>Aksi</th>
            {% endif %}
        </tr>
    </thead>
    {% if current_user.role == 'admin'  %}
    <a href="{{ url_for('main.tambah_produk') }}" class="btn btn-success mb-3">+ Tambah Products</a>
    {% endif %}

    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ product.name }}</td>
            <td>Rp {{ "{:,.0f}".format(product.price) }}</td>
            <td>{{ product.stock }}</td>
            <td>
                {% if product.image %}
                    <img src="{{ url_for('static', filename='product/' ~ product.image) }}" width="100">
                {% else %}
                    <span class="text-muted">Tidak ada gambar</span>
                {% endif %}
            </td>
            {% if current_user.role == 'admin'  %}
            <td>
                <a href="{{ url_for('main.edit_product', product_id=product.id) }}" class="btn btn-warning btn-sm">Edit</a>
                <a href="{{url_for('main.delete_product', product_id=product.id)}}" class="btn btn-danger btn-sm">Delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if products|length == 0 %}
        <tr>
            <td colspan="4" class="text-center">Tidak ada products tersedia</td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}

app/templates/product/tambah_produk.html
{% extends "layout.html" %}
{% block title %}Tambah Products{% endblock %}

{% block content %}
<h2 class="mb-4">Tambah Products Baru</h2>

<form method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="name" class="form-label">Nama Products</label>
        <input type="text" class="form-control" id="name" name="name" required>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Harga</label>
        <input type="number" class="form-control" id="price" name="price" required>
    </div>
    <div class="mb-3">
        <label for="stock" class="form-label">Stok</label>
        <input type="number" class="form-control" id="stock" name="stock" required min="0">
    </div>
    <div class="mb-3">
        <label for="image" class="form-label">Image</label>
        <input type="file" class="form-control" id="image" name="image" required>
    </div>    
    <button type="submit" class="btn btn-success">Simpan</button>
    <a href="{{ url_for('main.read_all_produk') }}" class="btn btn-secondary">Batal</a>
</form>
{% endblock %}